### ISSUE TITLE
Julia permission flags for security

### ISSUE THREAD

**Issue by aminya** [StefanKarpinski/Nefarious.jl#1]
[Deno](https://deno.land/manual/getting_started/permissions) takes an interesting approach to addressing this security issue. It provides permission flags such as 
--allow-read=some_folder
--allow-write
--allow-net
--allow-run
--allow-all
...

Julia can provide these kinds of flags in the future, if it wants to stay in the secure side of the things.

**Comment by StefanKarpinski** [comment]
Anything actionable on this repo here?

**Comment by aminya** [comment]
No this is an upstream thing. Since this package is a showcase about security, I find it relevant to the topic.
